### ISSUE TITLE
Код дерьмо

### ISSUE THREAD

**Issue by godunko-mikhail** [FregOnlyOne/ManageGoodsApp#1]
Всё хуйня.
хз с чего начать с того что у тебя мигации лежать на уровне папок паттерна или с того что у тебя switch case по строчкам в vm?

**Comment by FregOnlyOne** [comment]
Держи в курсе, дятел. Я знаю все косяки этого говнокода и без твоего
ебучего ревью, которое не просили.

**Comment by FregOnlyOne** [comment]
Иди выебывайся в свой двор.
